- name: Provisioning for tilda.center
  hosts: all
  pre_tasks:
    - include: roles/common/pre_tasks/main.yml
    - include: roles/docker/pre_tasks/main.yml
  roles:
    - postgresql
    - tilda
    - nginx

- name: Provisioning for tilda.center
  hosts: vagrant
  roles:
    - vagrant
