---
- name: update apt
  sudo: yes
  apt:
    update_cache: yes

- name: install common packages
  sudo: yes
  with_items: common_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: start docker
  sudo: yes
  service:
    name: docker
    enabled: yes
    state: started
