---
- name: disable firewalld
  sudo: yes
  service:
    name: firewalld
    enabled: no
    state: stopped

- name: install yum-utils
  sudo: yes
  yum:
    pkg: yum-utils
    state: latest

- name: enable public_ol6_latest
  sudo: yes
  command: yum-config-manager --enable public_ol6_latest

- name: install common packages
  sudo: yes
  with_items: common_packages
  yum:
    pkg: "{{ item.name }}"
    state: latest

- name: start docker
  sudo: yes
  service:
    name: docker
    enabled: yes
    state: started
